const data = [
  {
    key: '1',
    name: 'Fərhad Əmrah',
    age: 23,
    address: 'Bakı, N.Nərimanov rayonu',
    university: 'AzTU',
    eduType: 'əyani',
    status: 'məzun',
  },
  {
    key: '2',
    name: 'Rəvan Quliyev',
    age: 21,
    address: 'Bakı, Nizami rayonu',
    university: 'AzTU',
    eduType: 'əyani',
    status: 'təhsil alır',
  },
  {
    key: '4',
    name: 'Çinarə Abbaslı',
    age: 24,
    address: 'Quba rayonu',
    university: 'BDU',
    eduType: 'əyani',
    status: 'dondurulub',
  },
  {
    key: '3',
    name: 'Tunar Quluzadə',
    age: 19,
    address: 'Bakı, Nizami rayonu',
    university: 'BANM',
    eduType: 'əyani',
    status: 'təhsil alır',
  },
  {
    key: '5',
    name: 'Xədicə Məmmədova',
    age: 21,
    address: 'Bakı, Yasamal rayonu',
    university: 'ADNSU',
    eduType: 'qiyabi',
    status: 'təhsil alır',
  },
  {
    key: '6',
    name: 'Nicat Bayramlı',
    age: 25,
    address: 'Gəncə şəhəri',
    university: 'BANM',
    eduType: 'əyani',
    status: 'məzun',
  },
  {
    key: '7',
    name: 'Akif Musayev',
    age: 22,
    address: 'Bakı, Binəqədi rayonu',
    university: 'AzTU',
    eduType: 'qiyabi',
    status: 'dondurulub',
  },
  {
    key: '8',
    name: 'Banu Əliyeva',
    age: 27,
    address: 'Bakı, Xətai rayonu',
    university: 'BDU',
    eduType: 'əyani',
    status: 'məzun',
  },
];

export default data;
